### PR TITLE
fix: blog hero grid positioning and image loading

### LINKED ISSUE #192: 🐛 Bug: Blog images should be right-aligned on mobile
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/dot-com/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Blog images should be to the right of the h1, so they don't appear to be weirdly shoving the page down.

### Actual

Screenshot of the top half of a mobile page of a blog post. The circle hero image is above the h1.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #192
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/dot-com/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/dot-com/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

I ended up reworking the whole shebang to rely more on CSS Grid. To help with that I moved hero image sizing to base layer CSS variables.

Also augments `HeroImage` to have a tri-state for loading rather than boolean. Not strictly necessary for the work here but surprisingly helpful for debugging CSS class names loading.

### CODE REVIEW

File: src/components/HeroImage.tsx [hunk 1]
```diff
@@ -15,18 +15,24 @@ export interface HeroImageProps {
 	src: ColorSchemeImages | string;
 }
 
+type Load = "initial" | "loaded" | "loading";
```
Comment (JoshuaKGoldberg) [inline src/components/HeroImage.tsx:18]: Not technically necessary for this PR, but helpful for debugging in prod.
